"""Quarto pre-render hook: copy the repo-root figures into the project.

The canonical figures are generated by `pipeline.build_figures` into the
repo-root `figures/` directory, which lives OUTSIDE this Quarto project. Quarto
only bundles resources that live inside the project, so for the HTML website to
include the maps we copy them into `guide/figures/` before each render. The
copy is gitignored; the root `figures/` remains the single source of truth.
"""
from __future__ import annotations

import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "figures"
DST = HERE / "figures"


def main() -> None:
    if not SRC.exists():
        raise SystemExit(f"source figures not found: {SRC} (run pipeline.build_figures)")
    if DST.exists():
        shutil.rmtree(DST)
    shutil.copytree(SRC, DST)
    print(f"copied {SRC} -> {DST}")


if __name__ == "__main__":
    main()
